# Generated by Django 3.0.1 on 2020-02-08 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('notification_type', models.CharField(blank=True, choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('see', 'See')], max_length=50, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_creator', to=settings.AUTH_USER_MODEL, verbose_name='from')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='images.Image', verbose_name='image')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_to', to=settings.AUTH_USER_MODEL, verbose_name='to')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
