# Generated by Django 3.0.1 on 2020-03-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.Post', verbose_name='post'),
        ),
    ]
