from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^explore/$',
        view=views.ExploreUsers.as_view(),
        name='explore_users'
    ),
    url(
        regex=r'^(?P<user_id>[0-9]+)/follow/$',
        view=views.FollowUser.as_view(),
        name='follow_user'
    ),
    url(
        regex=r'^(?P<user_id>[0-9]+)/unfollow/$',
        view=views.UnFollowUser.as_view(),
        name='unfollow_user'
    ),
    url(
        regex=r'^(?P<user_id>[0-9]+)/block/$',
        view=views.BlockUser.as_view(),
        name='block_user'
    ),
    url(
        regex=r'^(?P<user_id>[0-9]+)/unblock/$',
        view=views.UnBlockUser.as_view(),
        name='unblock_user'
    ),
    url(
        regex=r'^(?P<username>\w+)/followers/$',
        view=views.UserFollowers.as_view(),
        name='user_followers'
    ),
    url(
        regex=r'^(?P<username>\w+)/following/$',
        view=views.UserFollowing.as_view(),
        name='user_following'
    ),
    url(
        regex=r'^(?P<username>\w+)/blockers/$',
        view=views.UserBlockers.as_view(),
        name='user_blockers'
    ),
    url(
        regex=r'^(?P<username>\w+)/blocking/$',
        view=views.UserBlocking.as_view(),
        name='user_blocking'
    ),
    url(
        regex=r'^(?P<username>\w+)/friends/$',
        view=views.UserFriends.as_view(),
        name='user_friends'
    ),
    url(
        regex=r'^search/$',
        view=views.Search.as_view(),
        name='search'
    ),
    url(
        regex=r'^(?P<username>\w+)/$',
        view=views.UserProfile.as_view(),
        name='user_profile'
    )
]
