// AUTHENTICATION ACTIONS
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// USER ACTIONS
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const SET_USER_LIST_REQUEST = 'SET_USER_LIST_REQUEST';
export const SET_USER_LIST_SUCCESS = 'SET_USER_LIST_SUCCESS';
export const SET_USER_LIST_FAILURE = 'SET_USER_LIST_FAILURE';
export const SET_POSTS_LIST_REQUEST = 'SET_POSTS_LIST_REQUEST';
export const SET_POSTS_LIST_SUCCESS = 'SET_POSTS_LIST_SUCCESS';
export const SET_POSTS_LIST_FAILURE = 'SET_POSTS_LIST_FAILURE';
export const BLOCK_USER = 'BLOCK_USER';
export const UNBLOCK_USER = 'UNBLOCK_USER';

// POSTS ACTIONS
export const LIKE = 'LIKE';
export const UNLIKE = 'UNLIKE';
export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';
export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE';
export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';
