# Generated by Django 3.0.1 on 2020-03-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='react',
            field=models.CharField(blank=True, choices=[('heart', 'heart'), ('joke', 'joke')], default='heart', max_length=6, verbose_name='React'),
        ),
    ]
