# Generated by Django 3.0.3 on 2020-04-09 12:24

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_token',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=250, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@]+$'), 'Username can only contain letters and numbers ', 'invalid')], verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=125, validators=[django.core.validators.RegexValidator(re.compile('^[\\w]+$'), 'Invalid name, can only contain letters.', 'invalid')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=125, validators=[django.core.validators.RegexValidator(re.compile('^[\\w]+$'), 'Invalid name, can only contain letters.', 'invalid')], verbose_name='last name'),
        ),
    ]
